#!/usr/bin/env bash

FIRST_ENTRY_STR="First line (password?)"
PASS_BIN=$(which pass)

function list_passwords {
    	shopt -s nullglob globstar
	    prefix=${PASSWORD_STORE_DIR-$HOME/.password-store}
    	password_files=( "$prefix"/**/*.gpg )
	    password_files=( "${password_files[@]#"$prefix"/}" )
    	password_files=( "${password_files[@]%.gpg}" )
    	printf "%s\n" "${password_files[@]}"
}

# list entries of password file $1
function list_password_entries {
        echo "$FIRST_ENTRY_STR"
		"$PASS_BIN" show "$1" | tail -n+2 | cut -s -d: -f1
}

# use rofi-dmenu to select an entry among those specified in $1
# $1 is a string with '\n' as entry separators
function select_entry {
    echo -ne "$1" | rofi -dmenu -p "entry"
}

# clip a entry $2 from a password file $1
function clip_entry {
    source <( awk '/clip\(\)/,/^}/{print}' "$PASS_BIN" )  # get clip function from pass
    source <( awk '1;/# BEGIN/{exit}' "$PASS_BIN" )  # get context of clip function from pass
    value=$("$PASS_BIN" show "$1" | grep -E "^$2:" | cut -s -d: -f2- | xargs)
    echo "VALUE: $value"
    clip "$value" "$1"
}

# copy (using pass) the entry $2 from password $1
function copy_entry {
    case "$2" in
        "$FIRST_ENTRY_STR")
            # Field is the standard password
            coproc ( "$PASS_BIN" show -c "$1" >/dev/null 2>&1 )
            ;;
        otpauth)
            # Field is in OTP format
            coproc ( "$PASS_BIN" otp -c "$1" >/dev/null 2>&1 )
            ;;
        *)
            clip_entry "$1" "$2"
            ;;
    esac
}

case "$ROFI_RETV" in
    0)
        # First call -> rofi-script mode
        list_passwords
        ;;
    1)
        # second call -> call back to activate rofi-dmenu mode
        ROFI_RETV=""
        coproc ( "$0" "$@" >/dev/null 2>&1 )
        ;;
    *)
        # last call -> rofi-dmenu mode
        entries=$(list_password_entries "$@")
        entry=$(select_entry "$entries")
        copy_entry "$@" "$entry"
       ;;
esac
