#!/usr/bin/env bash

FIRST_ENTRY_STR="First line (password?)"

case "$ROFI_RETV" in
    0)
    	# No argument -> first call
	    # list password files
    	shopt -s nullglob globstar
	    prefix=${PASSWORD_STORE_DIR-$HOME/.password-store}
    	password_files=( "$prefix"/**/*.gpg )
	    password_files=( "${password_files[@]#"$prefix"/}" )
    	password_files=( "${password_files[@]%.gpg}" )
    	printf "%s\n" "${password_files[@]}"
        ;;
    1)
        ROFI_RETV=""
        coproc ( "$0" $@ )
        ;;
    *)
        # call dmenu mode with list of entries
		entries=$(pass show "$@" | tail -n+2 | cut -s -d: -f1)
        entries="${FIRST_ENTRY_STR}\n${entries}"
        entry=$(echo -ne "$entries" | rofi -dmenu -p "entry")
		case "$entry" in
			"$FIRST_ENTRY_STR")
                echo standard pass
				# Field is the standard password
				coproc ( pass show -c "$@" >/dev/null 2>&1 )
				;;
			otpauth)
				# Field is in OTP format
				coproc ( pass otp -c "$@" >/dev/null 2>&1 )
				;;
			*)
				# Other fields
				# BUG: the name of the field is listed with the field content
				LINE=$(pass show "$@" | grep -n -E "^$entry:" | cut -s -d: -f1)
				coproc ( pass show -c"$LINE" "$@" >/dev/null 2>&1 )
				;;
		esac
        ;;
esac
